#!/bin/bash
#SBATCH -J SPADES_JOB
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --partition=shortq 
#SBATCH --mem=120G
#SBATCH -o %x-%j.out
#SBATCH -e %x-%j.err

#load modules 
module load SPAdes

echo "Run SPAdes with $SLURM_CPUS_PER_TASK cpus and $SLURM_MEM_PER_NODE Memory " 

metaspades.py -1 metag_1.fastq -2 metag_2.fastq -t $SLURM_CPUS_PER_TASK -m $SLURM_MEM_PER_NODE -o output.osd

echo "Done" 
